# Site settings
title: Saaketh Reddy
description: Personal Portfolio & Projects
author: Saaketh Reddy
email: saaketh09@gmail.com
url: "https://saakeechan.github.io"
baseurl: ""

# Navigation menu
navbar-links:
  Home: "/"
  Education: "education"
  Research: "research"
  Projects: "projects"
  Work Experience: "work-experience"


# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
